<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Page;

class PageSeeder extends Seeder
{
    public function run()
    {
        $pages = [
            [
                'slug' => 'contact',
                'title' => [
                    'en' => 'Contact Us',
                    'tl' => 'Makipag-ugnayan sa Amin'
                ],
                'content' => [
                    'en' => "Get in Touch with Us\n\nWe're here to help and answer any questions you might have. We look forward to hearing from you.\n\nLibrary Main Office\nAddress: 123 Bonifacio Street, Masantol, Pampanga, Philippines\nPhone: +63 917 123 4567\nEmail: info@library.com\n\nOperating Hours:\nMonday - Friday: 8:00 AM - 8:00 PM\nSaturday: 9:00 AM - 5:00 PM\nSunday: 10:00 AM - 4:00 PM\n\nReference Desk:\nPhone: +63 917 234 5678\nEmail: reference@library.com\n\nTechnical Support:\nEmail: support@library.com\n\nFor general inquiries, please email us at info@library.com or call our main office during operating hours. Our staff will be happy to assist you with:\n\n- Library card registration\n- Book reservations and renewals\n- Research assistance\n- Event information\n- Facility booking\n- General questions\n\nYou can also visit us in person at our main office. We're located in the heart of Masantol, easily accessible by public transportation.",
                    'tl' => "Makipag-ugnayan sa Amin\n\nNandito kami upang tumulong at sagutin ang anumang mga tanong na maaari ninyong mayroon. Inaasahan namin ang inyong pakikipag-ugnayan.\n\nPangunahing Opisina ng Aklatan\nAddress: 123 Bonifacio Street, Masantol, Pampanga, Philippines\nTelephono: +63 917 123 4567\nEmail: info@library.com\n\nOras ng Operasyon:\nLunes - Biyernes: 8:00 AM - 8:00 PM\nSabado: 9:00 AM - 5:00 PM\nLinggo: 10:00 AM - 4:00 PM\n\nReference Desk:\nTelephono: +63 917 234 5678\nEmail: reference@library.com\n\nTechnical Support:\nEmail: support@library.com\n\nPara sa pangkalahatang mga katanungan, mangyaring mag-email sa amin sa info@library.com o tumawag sa aming pangunahing opisina sa oras ng operasyon. Ang aming kawani ay maligayang tutulong sa inyo sa:\n\n- Pagpaparehistro ng library card\n- Pagreserba at pag-renew ng libro\n- Tulong sa pananaliksik\n- Impormasyon sa kaganapan\n- Pagbobook ng pasilidad\n- Pangkalahatang mga tanong\n\nMaaari din kayong bumisita sa amin nang personal sa aming pangunahing opisina. Kami ay matatagpuan sa puso ng Masantol, madaling maabot sa pamamagitan ng pampublikong transportasyon."
                ],
                'meta_description' => 'Contact the library for inquiries, assistance, and information',
                'is_active' => true,
            ],
            [
                'slug' => 'services',
                'title' => [
                    'en' => 'Library Services',
                    'tl' => 'Mga Serbisyo ng Aklatan'
                ],
                'content' => [
                    'en' => "Our Comprehensive Library Services\n\nCirculation Services\n- Book lending and returns\n- Material reservations\n- Inter-library loans\n- Overdue notifications\n- Library card issuance\n\nReference Services\n- Research assistance\n- Database searching guidance\n- Citation help\n- Information literacy instruction\n- One-on-one consultations\n\nDigital Services\n- Access to online databases\n- E-book lending\n- Digital archives\n- Online catalog\n- Remote access for registered members\n\nChildren's Services\n- Storytelling sessions\n- Reading programs\n- Educational workshops\n- Homework help\n- Age-appropriate collections\n\nStudy Facilities\n- Individual study carrels\n- Group study rooms\n- Computer workstations\n- Printing and scanning services\n- Free Wi-Fi access\n\nSpecial Collections\n- Local history archives\n- Rare books collection\n- Filipiniana section\n- Thesis and dissertation repository\n- Periodicals and newspapers\n\nCommunity Programs\n- Book clubs and reading groups\n- Author talks and lectures\n- Workshops and seminars\n- Cultural events\n- Technology training\n\nFor more information about any of these services, please contact our reference desk or visit the library during operating hours.",
                    'tl' => "Aming Komprehensibong Mga Serbisyo ng Aklatan\n\nCirculation Services\n- Paghiram at pagbabalik ng libro\n- Pagreserba ng materyales\n- Inter-library loans\n- Abiso sa overdue\n- Pagbibigay ng library card\n\nReference Services\n- Tulong sa pananaliksik\n- Gabay sa database searching\n- Tulong sa citation\n- Information literacy instruction\n- One-on-one consultations\n\nDigital Services\n- Access sa online databases\n- Paghiram ng e-book\n- Digital archives\n- Online catalog\n- Remote access para sa nakarehistrong miyembro\n\nMga Serbisyo para sa mga Bata\n- Storytelling sessions\n- Mga programa sa pagbabasa\n- Educational workshops\n- Tulong sa takdang-aralin\n- Mga koleksyon na angkop sa edad\n\nMga Pasilidad sa Pag-aaral\n- Individual study carrels\n- Group study rooms\n- Computer workstations\n- Printing at scanning services\n- Libreng Wi-Fi access\n\nSpesyal na Koleksyon\n- Local history archives\n- Koleksyon ng rare books\n- Filipiniana section\n- Thesis at dissertation repository\n- Periodicals at pahayagan\n\nMga Programa ng Komunidad\n- Book clubs at reading groups\n- Author talks at lectures\n- Workshops at seminars\n- Mga kaganapang pangkultura\n- Technology training\n\nPara sa karagdagang impormasyon tungkol sa alinman sa mga serbisyong ito, mangyaring makipag-ugnayan sa aming reference desk o bumisita sa aklatan sa oras ng operasyon."
                ],
                'meta_description' => 'Explore the comprehensive services offered by our library',
                'is_active' => true,
            ],
            [
                'slug' => 'membership',
                'title' => [
                    'en' => 'Library Membership',
                    'tl' => 'Pagiging Miyembro ng Aklatan'
                ],
                'content' => [
                    'en' => "Join Our Library Community\n\nBecome a library member and enjoy unlimited access to our resources and services!\n\nMembership Benefits:\n- Borrow up to 5 books for 14 days\n- Access to digital resources and e-books\n- Free Wi-Fi and computer use\n- Participation in library programs and events\n- Reservations for study rooms\n- Inter-library loan services\n\nMembership Types:\n\nStudent Membership (FREE)\n- Valid student ID required\n- Access to all regular services\n- Priority booking for study facilities\n- Extended borrowing during exam periods\n\nRegular Membership (FREE)\n- Available to all residents\n- Valid ID required\n- Full access to library services\n\nSenior Citizen Membership (FREE)\n- Age 60 and above\n- Extended loan periods\n- Home delivery service available\n- Special programs and activities\n\nHow to Register:\n1. Visit the library circulation desk\n2. Bring a valid ID (government-issued)\n3. Fill out the membership form\n4. Get your library card instantly\n\nRequired Documents:\n- Government-issued ID (Passport, Driver's License, National ID)\n- For students: Valid student ID\n- For senior citizens: Senior Citizen ID\n- Proof of address (utility bill or barangay certificate)\n\nRules and Responsibilities:\n- Return borrowed materials on time\n- Handle library materials with care\n- Keep your library card secure\n- Notify us of address or contact changes\n- Pay fines for overdue or damaged materials\n\nLibrary Card Replacement:\nLost or damaged cards can be replaced for a fee of ₱100. Please report lost cards immediately to prevent unauthorized use.\n\nFor more information, contact us at membership@library.com or visit the circulation desk.",
                    'tl' => "Sumali sa Aming Komunidad ng Aklatan\n\nMaging miyembro ng aklatan at tamasahin ang walang hanggang access sa aming mga resources at serbisyo!\n\nMga Benepisyo ng Pagiging Miyembro:\n- Humiram ng hanggang 5 libro para sa 14 na araw\n- Access sa digital resources at e-books\n- Libreng Wi-Fi at paggamit ng computer\n- Paglahok sa mga programa at kaganapan ng aklatan\n- Pagreserba para sa study rooms\n- Inter-library loan services\n\nUri ng Membership:\n\nStudent Membership (LIBRE)\n- Kinakailangan ang valid student ID\n- Access sa lahat ng regular na serbisyo\n- Priority booking para sa study facilities\n- Extended borrowing sa panahon ng exam\n\nRegular Membership (LIBRE)\n- Available sa lahat ng residente\n- Kinakailangan ang valid ID\n- Buong access sa library services\n\nSenior Citizen Membership (LIBRE)\n- Edad 60 pataas\n- Extended loan periods\n- Available ang home delivery service\n- Espesyal na programa at aktibidad\n\nParaan ng Pagpaparehistro:\n1. Bumisita sa circulation desk ng aklatan\n2. Magdala ng valid ID (government-issued)\n3. Punan ang membership form\n4. Kunin ang inyong library card kaagad\n\nKinakailangang Dokumento:\n- Government-issued ID (Passport, Driver's License, National ID)\n- Para sa mga estudyante: Valid student ID\n- Para sa senior citizens: Senior Citizen ID\n- Proof of address (utility bill o barangay certificate)\n\nMga Patakaran at Responsibilidad:\n- Ibalik ang mga hiniram na materyales sa takdang oras\n- Alagaan ang mga library materials\n- Panatilihing ligtas ang inyong library card\n- Ipaalam sa amin ang pagbabago ng address o contact\n- Magbayad ng multa para sa overdue o sirang materyales\n\nPagpapalit ng Library Card:\nAng nawala o sirang cards ay maaaring palitan sa bayad na ₱100. Mangyaring iulat kaagad ang nawalang cards upang maiwasan ang hindi awtorisadong paggamit.\n\nPara sa karagdagang impormasyon, makipag-ugnayan sa amin sa membership@library.com o bumisita sa circulation desk."
                ],
                'meta_description' => 'Learn about library membership benefits and how to join',
                'is_active' => true,
            ],
            [
                'slug' => 'faq',
                'title' => [
                    'en' => 'Frequently Asked Questions',
                    'tl' => 'Mga Madalas Itanong'
                ],
                'content' => [
                    'en' => "Frequently Asked Questions\n\nGeneral Questions:\n\nQ: How do I get a library card?\nA: Visit our circulation desk with a valid ID and proof of address. Registration is free and your card will be issued immediately.\n\nQ: What are your operating hours?\nA: Monday-Friday: 8:00 AM - 8:00 PM, Saturday: 9:00 AM - 5:00 PM, Sunday: 10:00 AM - 4:00 PM\n\nQ: Is library membership free?\nA: Yes! All types of library membership are completely free for residents.\n\nBorrowing Questions:\n\nQ: How many books can I borrow?\nA: Members can borrow up to 5 books at a time for a period of 14 days.\n\nQ: Can I renew my borrowed books?\nA: Yes, books can be renewed once for an additional 14 days if no one has reserved them.\n\nQ: What happens if I return books late?\nA: A fine of ₱5 per day per book will be charged for overdue materials.\n\nQ: Can I reserve books?\nA: Yes! You can reserve books online through our catalog or at the circulation desk.\n\nDigital Services:\n\nQ: How do I access e-books?\nA: Use your library card number and PIN to log in to our digital library portal.\n\nQ: Can I access databases from home?\nA: Yes, registered members can access our online databases remotely using their library credentials.\n\nQ: Is there Wi-Fi in the library?\nA: Yes, free Wi-Fi is available throughout the library. Connect to 'Library_WiFi' and use your library card credentials.\n\nFacilities:\n\nQ: Can I reserve a study room?\nA: Yes, study rooms can be reserved up to 7 days in advance through our website or at the reference desk.\n\nQ: Are there computers available for public use?\nA: Yes, we have 20 computer workstations available on a first-come, first-served basis. Sessions are limited to 2 hours.\n\nQ: Can I print and photocopy at the library?\nA: Yes, printing and photocopying services are available for a small fee: ₱2 per page (B&W), ₱5 per page (color).\n\nFor more questions, contact us at info@library.com or call +63 917 123 4567.",
                    'tl' => "Mga Madalas Itanong\n\nPangkalahatang Mga Tanong:\n\nQ: Paano ako makakakuha ng library card?\nA: Bumisita sa aming circulation desk na may valid ID at proof of address. Ang registration ay libre at ang inyong card ay ibibigay kaagad.\n\nQ: Ano ang inyong oras ng operasyon?\nA: Lunes-Biyernes: 8:00 AM - 8:00 PM, Sabado: 9:00 AM - 5:00 PM, Linggo: 10:00 AM - 4:00 PM\n\nQ: Libre ba ang library membership?\nA: Oo! Lahat ng uri ng library membership ay ganap na libre para sa mga residente.\n\nMga Tanong sa Paghiram:\n\nQ: Ilang libro ang maaari kong hiramin?\nA: Ang mga miyembro ay maaaring humiram ng hanggang 5 libro sa isang pagkakataon para sa 14 na araw.\n\nQ: Maaari ko bang i-renew ang aking mga hiniram na libro?\nA: Oo, ang mga libro ay maaaring i-renew ng isang beses para sa karagdagang 14 na araw kung walang nag-reserve sa kanila.\n\nQ: Ano ang mangyayari kung mahuli ako sa pagbabalik ng libro?\nA: Ang multa na ₱5 bawat araw bawat libro ay sisingilin para sa overdue materials.\n\nQ: Maaari ba akong mag-reserve ng mga libro?\nA: Oo! Maaari kayong mag-reserve ng mga libro online sa pamamagitan ng aming catalog o sa circulation desk.\n\nDigital Services:\n\nQ: Paano ko maa-access ang mga e-book?\nA: Gamitin ang inyong library card number at PIN upang mag-log in sa aming digital library portal.\n\nQ: Maaari ko bang i-access ang mga database mula sa bahay?\nA: Oo, ang mga nakarehistrong miyembro ay maaaring mag-access ng aming online databases nang remote gamit ang kanilang library credentials.\n\nQ: Mayroon bang Wi-Fi sa aklatan?\nA: Oo, ang libreng Wi-Fi ay available sa buong aklatan. Kumonekta sa 'Library_WiFi' at gamitin ang inyong library card credentials.\n\nMga Pasilidad:\n\nQ: Maaari ba akong mag-reserve ng study room?\nA: Oo, ang study rooms ay maaaring i-reserve hanggang 7 araw nang maaga sa pamamagitan ng aming website o sa reference desk.\n\nQ: Mayroon bang mga computer na available para sa pampublikong paggamit?\nA: Oo, mayroon kaming 20 computer workstations na available sa first-come, first-served basis. Ang sessions ay limitado sa 2 oras.\n\nQ: Maaari ba akong mag-print at mag-photocopy sa aklatan?\nA: Oo, ang printing at photocopying services ay available para sa maliit na bayad: ₱2 bawat pahina (B&W), ₱5 bawat pahina (kulay).\n\nPara sa higit pang mga tanong, makipag-ugnayan sa amin sa info@library.com o tumawag sa +63 917 123 4567."
                ],
                'meta_description' => 'Find answers to commonly asked questions about our library',
                'is_active' => true,
            ],
        ];

        foreach ($pages as $page) {
            Page::create($page);
        }

        $this->command->info('Pages seeded successfully!');
    }
}